---
- name: Configure database server
  hosts: database_servers
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server

    - name: "Install Python packages"
      yum: "name={{ item }} state=present"
      with_items:
        - python3-psycopg2

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists
 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: "Create database and table"
      become_user: postgres
      shell: |
        psql -c "CREATE DATABASE mydatabase;"
        psql -d mydatabase -c "CREATE TABLE mytable (id SERIAL PRIMARY KEY, data VARCHAR(100));"

    - name: "Change PostgreSQL port"
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^port = '
        line: 'port = 7290'

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
